# This workflow runs the CI command defined in package.json
name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      PRIVATE_ALCHEMY_ID: ${{ secrets.PRIVATE_ALCHEMY_ID }}
      ANVIL_BLOCK_NUMBER: 16522514
      ANVIL_FORK_URL: https://eth-mainnet.alchemyapi.io/v2/${{ secrets.PRIVATE_ALCHEMY_ID }}
    steps:
      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v3

      - name: üì¶ Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.15

      - name: üì¶ Setup Node 18
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 18

      - name: üíæ Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
            apps/**/node_modules
            packages/**/node_modules
            packages/**/dist
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: ‚è¨ Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i

      - name: üíæ Cache Anvil
        uses: 'actions/cache@v3'
        with:
          path: ~/.foundry/cache/rpc/**/${{ env.ANVIL_BLOCK_NUMBER }}
          key: foundry-anvil-${{ env.ANVIL_BLOCK_NUMBER }}

      - name: üëæ Run lint task
        run: pnpm lint

      - name: üëæ Run type check task
        run: pnpm type-check

      - name: ü¶Ä Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      - name: üî® Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: üöÄ Launch Anvil
        run: anvil --fork-url $ANVIL_FORK_URL --fork-block-number $ANVIL_BLOCK_NUMBER &

      - name: üëæ Run test task
        run: pnpm test

      # Need to shutdown Anvil so cache gets created
      - name: üí§ Shutdown Anvil
        run: pkill -2 anvil

# TODO @0xMillz for production: (https://vercel.com/guides/how-can-i-use-github-actions-with-vercel)
#name: Vercel Production Deployment
#env:
#  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#on:
#  push:
#    branches:
#      - main
#jobs:
#  Deploy-Production:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install Vercel CLI
#        run: npm install --global vercel@latest
#      - name: Pull Vercel Environment Information
#        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
#      - name: Build Project Artifacts
#        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
#      - name: Deploy Project Artifacts to Vercel
#        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
